language: ruby
rvm:
  - 2.2.0

addons:
  postgresql: "9.3"

# config/database.yml in Rails
test:
  adapter: postgresql
  database: open_call_test
  username: postgres

before_script:
  - psql -c 'create database open_call_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV="test"